model:
  working_dir: './data'
  batch_size: 16

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_{}"

training:
  learning_rate: 1e-3
  decay: 1e+3
  log_dir: 'logs/{}_{}'
  epochs: 50