model:
  working_dir: "/home/pravesh/speech_work/ETA/models/ETA/data"
  batch_size: 8
  training_label: "small_eta/dcrnn/custom_new/missing/dot_gaussian/trans1"
  num_nodes: 1165
  steps_to_predict: 12
  graph_batch_size: 256
  static_data_dir: "static"
  ttr: 1

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_new_{}"
  mean:
    - 1.92559222
    - 0.56999187
  std:
    - 1.29298016
    - 0.17494257

training:
  learning_rate: 0.001
  decay: 1e+3
  log_dir: "logs/{}"
  ckpt_dir: "ckpt/{}"
  epochs: 100
  reset: False
