model:
  working_dir: './data'
  batch_size: 256
  training_label: "dcrnn_baseline_sampling"
  static_data_dir: 'static'
  num_nodes: 6639
  counter_position: 0
  teacher_decay_rate: 2000
  graph_batch_size: 50
  steps_to_predict: 6


data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_{}"
  mean: 
    - 1.3395504
    - 0.49493809

  std:
    - 1.64047834
    - 0.28855661

training:
  learning_rate: 0.01
  decay: 1e+3
  log_dir: 'logs/{}'
  ckpt_dir: 'ckpt/{}'
  epochs: 50
  reset: False