model:
  working_dir: "./data"
  batch_size: 16
  training_label: "results/dcrnn/custom/final"
  num_nodes: 6639
  steps_to_predict: 6
  graph_batch_size: 256
  static_data_dir: "static"
  ttr: 1

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_{}"
  mean:
    - 1.3395504
    - 0.49493809
  std:
    - 1.64047834
    - 0.28855661

training:
  learning_rate: 0.001
  decay: 1e+3
  log_dir: "logs/{}"
  ckpt_dir: "ckpt/{}"
  epochs: 50
  reset: False
