model:
  working_dir: "./data"
  batch_size: 16
  training_label: "small_eta/dcrnn/784/128/sum/2"
  num_nodes: 784
  steps_to_predict: 6
  graph_batch_size: 128
  static_data_dir: "static"
  ttr: 1

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_{}"
  mean:
    - 1.45362457
    - 0.53708629
  std:
    - 1.65967594
    - 0.26022761

training:
  learning_rate: 0.00005
  decay: 1e+3
  log_dir: "logs/{}"
  ckpt_dir: "ckpt/{}"
  epochs: 100
  reset: False
