model:
  working_dir: "./data"
  batch_size: 16
  training_label: "results/lstm"
  num_nodes: 6639
  steps_to_predict: 6
  ttr: 1

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_{}"
  mean:
    - 54.405
    - 0.497
  std:
    - 19.493
    - 0.288

training:
  learning_rate: 0.0001
  decay: 1e+3
  log_dir: "logs/{}"
  ckpt_dir: "ckpt/{}"
  epochs: 50
  reset: False
