model:
  working_dir: "/home/pravesh/speech_work/ETA/models/ETA/data"
  batch_size: 16
  training_label: "small_eta/eta/spearson/0.0001/dot/decay"
  num_nodes: 1165
  steps_to_predict: 12
  graph_batch_size: 256
  static_data_dir: "static"
  ttr: 1

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_new_{}"
  mean:
    - 2.13771687
    - 0.5744334
  std:
    - 2.04323081
    - 0.17708756

training:
  learning_rate: 0.0001
  decay: 1e+3
  log_dir: "logs/{}"
  ckpt_dir: "ckpt/{}"
  epochs: 100
  reset: False
