model:
  working_dir: './data'
  batch_size: 64
  training_label: "melr_dcrnn"
  static_data_dir: 'static'
  num_nodes: 207
  counter_position: 0
  teacher_decay_rate: 2000


data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "melr_{}"
  mean: 
    - 54.405
    - 0.497
  std:
    - 19.493
    - 0.288

training:
  learning_rate: 0.01
  decay: 1e+3
  log_dir: 'logs/{}'
  ckpt_dir: 'ckpt/{}'
  epochs: 50
  reset: False