model:
  working_dir: './data'
  batch_size: 16
  training_label: "lstm_with_conv1d"

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "custom_{}"

training:
  learning_rate: 0.001
  decay: 1e+3
  log_dir: 'logs/{}'
  ckpt_dir: 'ckpt/{}'
  epochs: 50