model:
  working_dir: "./data"
  batch_size: 16
  training_label: "lstm_conv1d_melr/DC/7"
  num_nodes: 207
  steps_to_predict: 12
  ttr: 1

data:
  shuffle: 1000
  prefetch: 10
  path_pattern: "training_files"
  split_prefix: "melr_{}"
  mean:
    - 54.405
    - 0.497
  std:
    - 19.493
    - 0.288

training:
  learning_rate: 0.00001
  decay: 1e+3
  log_dir: "logs/{}"
  ckpt_dir: "ckpt/{}"
  epochs: 50
  reset: False
